### PR TITLE
Update etl_export_step5.R

### PR DESCRIPTION
**Pull request by juruchi**
The following error occurred in ```etl_export_step5```'s valid_coverage test when attempting to generate the final codebook for #82:

```
Error in `map_lgl()`:
ℹ In index: 1.
Caused by error in `UseMethod()`:
! no applicable method for 'select' applied to an object of class "NULL"
Run `rlang::last_error()` to see where the error occurred.
```

I believe this is because no index of 3 exists for this dataset.

### CODE REVIEW

**Comment by ran-codes** [comment]
thanks @juruchi. taking a look now. 😄

**Comment by ran-codes** [comment]
mmm it seems to work for me. see log

```
>   etl_APS_MONTH_v1.0(etl)
✔ Lock file in sync with server                                                            
✔ APS_MONTH_v1.0 data already frozen.
ℹ Importing APS_MONTH_v1.0 files.
→ Read into raw_data - APSISO2_MONTH_12142022.parquet
→ Read into raw_data - APSL1AD_MONTH_12142022.parquet
→ Read into raw_data - APSL1UX_MONTH_12142022.parquet
→ Read into raw_data - APSL2_MONTH_12142022.parquet

── Start Renovation APS_MONTH_v1.0 ─────────────────────
ℹ Step 1 (Variable list)
→ df_var_name validated
→ Wrote var_name.csv for APS_MONTH
✔ Success
ℹ Step 2 (Strata metadata)
→ df_strata validated.
→ Wrote strata.csv for APS_MONTH
✔ Success
Joining with `by = join_by(iso2)`
ℹ Step 3 (Data formatting)
→ Valid df_data_sample
→ Wrote data for APS_MONTH
✔ Success
ℹ Step 4 (Schema + template generation)
→ Valid linkage.csv
✔ Success
ℹ Step 5a (raw -> base codebooks)
✔ Valid base codebooks; export success!
ℹ Step 5b (int -> final codebooks)
✔ Valid final codebooks; export success!
ℹ Step 6 (Denormalization)
→ denormalization of APS_MONTH with by_dataset
→ denormalization of APS_MONTH with by_var
✔ Valid denormalized tables
✔ Staged: APS_MONTH_denorm_subset.parquet
✔ APS_MONTH_v1.0 Renovation Done! (cycle: final_codebooks)
```

quick zoom call to debug?

**Comment by ran-codes** [comment]
jk. the point was that it was fixed. (sorry haha just back from vacation.)!

Thanks! merging!

**Comment by ran-codes** [comment]
@juruchi whats the difference between map and imap and why it fixed the problem?

**Comment by juruchi** [comment]
Sorry for the late response. imap is an indexed map so you can use both the value and position of an element. I believe that when the validation test was created, it was based on a specific test case? One that had at least 3 sheets in the codebook? My  understanding is that the test would look over every sheet in the codebook and make sure nothing had been dropped from the previous codebook version. From what I saw before switching to imap, the test was actually only searching through the third sheet of the codebook and making the comparison. Since the APS_MONTH only has two sheets in the codebook, the test could not be completed and an error was thrown.

**Comment by ran-codes** [comment]
o wow.... this is actually really useful! I've always hacked my way around named lists in purrr. Really elegant solution. thanks for the explanation!

**Pull request merged**
